version: "3"
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=changeme
      - RABBITMQ_DEFAULT_PASS=changeme
    ports:
      - "127.0.0.1:5672:5672"

  redis:
    hostname: redis
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

  producer:
    hostname: producer
    build: ./producer
    container_name: producer
    environment:
      - BROKER_AUTH=changeme:changeme
      - BROKER_URL=rabbitmq:5672
      - BACKEND_URL=redis:6379
      - LOGLEVEL=info
    depends_on:
      - rabbitmq
      - redis

  worker1:
    hostname: worker1
    build: ./consumer
    container_name: worker1
    environment:
      - BROKER_AUTH=changeme:changeme
      - BROKER_URL=rabbitmq:5672
      - BACKEND_URL=redis:6379
      - CONCURRENCY=2
      - LOGLEVEL=info
    depends_on:
      - rabbitmq
      - redis

  worker2:
    hostname: worker2
    build: ./consumer
    container_name: worker2
    environment:
      - BROKER_AUTH=changeme:changeme
      - BROKER_URL=rabbitmq:5672
      - BACKEND_URL=redis:6379
      - CONCURRENCY=2
      - LOGLEVEL=info
    depends_on:
      - rabbitmq
      - redis
