version: "3"
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=changeme
      - RABBITMQ_DEFAULT_PASS=changeme
    ports:
      - "127.0.0.1:5672:5672"

  redis:
    hostname: redis
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

  producer:
    hostname: producer
    build: ./producer
    container_name: producer
    environment:
      - BROKER_USER=changeme
      - BROKER_PASS=changeme
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=5672
      - BACKEND_HOST=redis
      - BACKEND_PORT=6379
    depends_on:
      - rabbitmq
      - redis

  worker:
    hostname: worker
    build: ./consumer
    environment:
      - BROKER_USER=changeme
      - BROKER_PASS=changeme
      - BROKER_HOST=rabbitmq
      - BROKER_PORT=5672
      - BACKEND_HOST=redis
      - BACKEND_PORT=6379
      - CONCURRENCY=2
      - LOGLEVEL=info
    depends_on:
      - rabbitmq
      - redis
    scale: 2
